"use client";

import { useCallback, useEffect, useState } from "react";
import { AvatarPanel } from "@/components/avatar/AvatarPanel";
import type { PerxonaPresenterHandle } from "@/components/avatar/PerxonaPresenter";
import { ChatPanel } from "@/components/chat/ChatPanel";
import { KnowledgePanel } from "@/components/rag/KnowledgePanel";

type Health = { ok: boolean; services: { llmConfigured: boolean; embeddingsConfigured: boolean; perxonaConfigured: boolean } };
export default function HomePage() { const [health, setHealth] = useState<Health | null>(null); const [presenter, setPresenter] = useState<PerxonaPresenterHandle | null>(null); const connectPresenter = useCallback((value: PerxonaPresenterHandle | null) => setPresenter(value), []); useEffect(() => { void fetch("/api/health").then((response) => response.json()).then(setHealth).catch(() => setHealth(null)); }, []); return <main className="mx-auto min-h-screen max-w-7xl px-5 py-8"><header className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-[0.25em] text-mint">Perxona starter</p><h1 className="mt-2 text-4xl font-bold tracking-tight">Hackathon conversation template</h1><p className="mt-2 max-w-2xl text-slate-600">A small, provider-agnostic chat, RAG, and avatar demo. Configure credentials in .env.local, then use this page as the foundation for your idea.</p></div><div className="rounded-xl bg-white p-4 text-sm shadow-sm"><p className="mb-2 font-semibold">Service status</p>{health ? <div className="grid gap-1 text-slate-600"><span>LLM: {health.services.llmConfigured ? "configured" : "not configured"}</span><span>Embeddings: {health.services.embeddingsConfigured ? "configured" : "not configured"}</span><span>Perxona: {health.services.perxonaConfigured ? "configured" : "not configured"}</span></div> : <span className="text-slate-500">Health unavailable</span>}</div></header><div className="grid gap-5 lg:grid-cols-2"><AvatarPanel onPresenterReady={connectPresenter} /><ChatPanel onAnswer={(answer) => { presenter?.present(answer).catch(() => undefined); }} /></div><div className="mt-5"><KnowledgePanel /></div></main>; }
