"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { PerxonaPresenter, type PerxonaPresenterHandle, type PresenterStatus } from "./PerxonaPresenter";
import type { PresentationTarget } from "@/lib/perxona/presenter.types";

type Item = { id: string; name?: string };
const labels: Record<PresenterStatus, string> = { "not-configured": "Not configured", initializing: "Initializing", ready: "Ready", speaking: "Speaking", error: "Error" };

export function AvatarPanel({ onPresenterReady }: { onPresenterReady: (presenter: PerxonaPresenterHandle | null) => void }) {
  const presenterRef = useRef<PerxonaPresenterHandle>(null);
  const [presenterUrl, setPresenterUrl] = useState(""); const [target, setTarget] = useState<PresentationTarget | null>(null); const [status, setStatus] = useState<PresenterStatus>("not-configured"); const [message, setMessage] = useState(""); const [motions, setMotions] = useState<Item[]>([]); const [motionId, setMotionId] = useState("");
  const statusChanged = useCallback((next: PresenterStatus, detail?: string) => { setStatus(next); setMessage(detail || ""); }, []);
  useEffect(() => { let active = true; async function load() { try { const config = await (await fetch("/api/perxona/config")).json() as { presenterUrl: string; target: PresentationTarget | null; configured: boolean }; if (!active) return; setPresenterUrl(config.presenterUrl); if (config.target) setTarget(config.target); else if (config.configured) { const [avatars, scenes, voices] = await Promise.all([fetch("/api/perxona/avatars").then((r) => r.json()), fetch("/api/perxona/scenes").then((r) => r.json()), fetch("/api/perxona/voices").then((r) => r.json())]); const avatar = (avatars.items as Item[] | undefined)?.[0]; const scene = (scenes.items as Item[] | undefined)?.[0]; const voice = (voices.items as Item[] | undefined)?.[0]; if (avatar && scene) setTarget({ avatarId: avatar.id, sceneId: scene.id, ...(voice ? { voiceId: voice.id } : {}) }); } if (!config.configured) setMessage("Set Perxona keys to enable the avatar."); } catch (error) { if (active) statusChanged("error", error instanceof Error ? error.message : "Could not load Perxona configuration."); } } void load(); return () => { active = false; }; }, [statusChanged]);
  useEffect(() => { if (!target?.avatarId) return; void fetch(`/api/perxona/avatars/${encodeURIComponent(target.avatarId)}/motions`).then((r) => r.json()).then((body: { items?: Item[] }) => setMotions(body.items || [])).catch(() => setMotions([])); }, [target?.avatarId]);
  useEffect(() => { onPresenterReady(presenterRef.current); return () => onPresenterReady(null); }, [onPresenterReady, presenterRef]);
  return <section className="rounded-2xl bg-ink p-5 text-white shadow-sm"><div className="mb-4 flex items-center justify-between"><div><p className="text-xs uppercase tracking-[0.2em] text-slate-300">Perxona avatar</p><h2 className="text-xl font-semibold">Presenter</h2></div><span className={`rounded-full px-3 py-1 text-xs ${status === "error" ? "bg-red-400/20 text-red-200" : "bg-white/10 text-slate-200"}`}>{labels[status]}</span></div><div className="mb-4 flex min-h-56 items-center justify-center rounded-xl bg-slate-900/70"><PerxonaPresenter ref={presenterRef} presenterUrl={presenterUrl} target={target} onStatus={statusChanged} /></div>{message && <p className="mb-3 text-sm text-slate-300">{message}</p>}<button className="w-full rounded-lg bg-mint px-4 py-2 font-semibold text-white disabled:cursor-not-allowed disabled:opacity-50" disabled={!target || !presenterUrl} onClick={() => void presenterRef.current?.initialize()}>Initialize / unlock audio</button><div className="mt-4 grid grid-cols-[1fr_auto] gap-2"><select className="rounded-lg border-0 bg-white/10 px-3 py-2 text-sm text-white" value={motionId} onChange={(event) => setMotionId(event.target.value)}><option value="" className="text-ink">Choose available motion</option>{motions.map((motion) => <option className="text-ink" key={motion.id} value={motion.id}>{motion.name || motion.id}</option>)}</select><button className="rounded-lg bg-white/10 px-3 py-2 text-sm disabled:opacity-40" disabled={!motionId} onClick={() => presenterRef.current?.playMotion(motionId).catch((error: Error) => statusChanged("error", error.message))}>Play</button></div></section>;
}
